In [3]:
x = [46,265,2658,-456,4668]

In [4]:
x

[46, 265, 2658, -456, 4668]

In [5]:
type(x)

list

In [6]:
import numpy as np

In [7]:
a = np.array(x)

In [8]:
a

array([  46,  265, 2658, -456, 4668])

In [9]:
type(a)

numpy.ndarray

In [10]:
len(a)

5

In [11]:
a.max()

4668

In [12]:
a.mean()

1436.2

In [13]:
a.min()

-456

In [15]:
a.argmin()

3

In [16]:
y = [12,2356.56,True,'Hello']

In [17]:
type(y)

list

In [18]:
b = np.array(y)

In [19]:
b

array(['12', '2356.56', 'True', 'Hello'], dtype='<U32')

In [20]:
z = [12,23,154,1.466]

In [21]:
c = np.array(z)

In [22]:
c

array([ 12.   ,  23.   , 154.   ,   1.466])

In [23]:
e = [122,455,85,True,False]

In [24]:
e

[122, 455, 85, True, False]

In [25]:
d = np.array(e)

In [26]:
d

array([122, 455,  85,   1,   0])